proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: scientists
  users:
    - name: jack
      password: password
      groups: scientists
    - name: jeff
      password: password
      groups: mathematicians
  specs:
    - id: flaskapp_demo  # Unique ID for your app
      display-name: "automation_booysendal"  # Display name for your app
      container-image: flask-test  # The name of your Docker image
      port: 8080
      container-env:
        # Environment variables required by your app, if any
        DATABASE_URL: 'postgresql://doadmin:a111y86khewpcb12@db-postgresql-lon1-73867-do-user-3909794-0.b.db.ondigitalocean.com:25060/DB_Booysendal_GVR?sslmode=require'
      access-groups: [scientists, mathematicians]  # Groups that can access this app
logging:
  file:
    name: shinyproxy.log

